---
# tasks file for roles/haproxy
- name: Install Haproxy on Centos
  yum: 
    name: haproxy
  when: ansible_distribution == 'CentOS'

- name: Install Haproxy on ubuntu
  apt: 
    name: haproxy
  when: ansible_distribution == 'Ubuntu'

- name: Config haproxy
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy